### ISSUE TITLE
fix signup page error check 

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSDWebsite#15]
make sure stripe works when validating cc

**Comment by aeolyus** [comment]
That's the credit card expiration date. We need to do a test with an actual credit card with the Stripe API to verify.

**Comment by aeolyus** [comment]
On page alert added with commit 5a6ab4dd31d6b2e428d6e37fe37c8cc44ac90a19

**Comment by varmichelle** [comment]
fixed by 1c7e0f6

**Comment by aeolyus** [comment]
We still need to get this working first, preferably with a real credit card, before we close the issue.

**Comment by aeolyus** [comment]
#35
