### ISSUE TITLE
routing home (instead of success) after submitting signup form

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSDWebsite#25]

**Comment by aeolyus** [comment]
Shouldn't we let them know that they actually made an account though? Maybe we could do the same thing as #13

**Comment by aeolyus** [comment]
`Materialize.toast()`

**Comment by varmichelle** [comment]
error seems to be introduced after the "signup revamp" commit e0b0c3d

**Comment by aeolyus** [comment]
Find the differences between the files of the commit by using `git diff`

**Comment by varmichelle** [comment]
not entirely fixed. no longer routes home, but still doesn't route to success
